// =============================================================================
// Module  : rmii_rx
// Project : Tang Nano 9K – PID Motor Controller over Ethernet
// File    : rtl/rmii_rx.v
//
// Purpose : RMII (Reduced Media Independent Interface) receive path.
//           Converts 2-bit dibits arriving at 50 MHz into an 8-bit byte
//           stream with SoF / EoF / valid handshake signals.
//
//           RMII 100 Mbps encoding:
//             Clock : 50 MHz REF_CLK (generated by LAN8720, fed to FPGA)
//             Data  : 2 bits per clock (RXD[1:0])  → 4 clk per byte
//             Preamble: 7 bytes of 0x55 = repeated dibits 2'b01 (28 cycles)
//             SFD     : 0xD5 – last dibit is 2'b11
//             Data    : user bytes, LSB of each byte arrives first
//
// Interface
//   clk50      – 50 MHz RMII reference clock (from LAN8720 INT/REFCLK pin)
//   rst        – Synchronous active-high reset
//   crs_dv     – CRS/DV combined signal from LAN8720
//   rxd[1:0]   – RMII receive data (2 bits)
//   rx_er      – RMII receive error (tie to GND if not connected)
//   sof        – Start-of-frame pulse (1 cycle, marks first data byte)
//   eof        – End-of-frame pulse (1 cycle, after last data byte incl. FCS)
//   vld        – Byte valid strobe
//   byte_out   – Received byte (valid when vld=1)
// =============================================================================

`default_nettype none

module rmii_rx (
    input  wire       clk50,
    input  wire       rst,
    input  wire       crs_dv,
    input  wire [1:0] rxd,
    input  wire       rx_er,    // tie to 1'b0 if not wired
    output reg        sof,
    output reg        eof,
    output reg        vld,
    output reg  [7:0] byte_out
);

    // -------------------------------------------------------------------------
    // State machine
    // -------------------------------------------------------------------------
    localparam S_IDLE     = 2'd0;
    localparam S_PREAMBLE = 2'd1;
    localparam S_DATA     = 2'd2;

    reg [1:0] state;
    reg [1:0] dcnt;      // dibit counter within a byte (0..3)
    reg [5:0] accum;     // accumulates bits[5:0] while building byte

    always @(posedge clk50) begin
        // Default – deassert strobes every cycle
        sof <= 1'b0;
        eof <= 1'b0;
        vld <= 1'b0;

        if (rst) begin
            state    <= S_IDLE;
            dcnt     <= 2'd0;
            accum    <= 6'd0;
        end else begin
            case (state)

                // ------------------------------------------------------------------
                // IDLE: wait for carrier sense + first preamble dibit (01)
                // ------------------------------------------------------------------
                S_IDLE: begin
                    if (crs_dv && rxd == 2'b01)
                        state <= S_PREAMBLE;
                end

                // ------------------------------------------------------------------
                // PREAMBLE: eat 01-dibits until SFD termination dibit (11)
                // ------------------------------------------------------------------
                S_PREAMBLE: begin
                    if (!crs_dv) begin
                        state <= S_IDLE;   // lost carrier during preamble – abort
                    end else if (rxd == 2'b11) begin
                        // End of SFD (0xD5); next dibit is first data byte bit[1:0]
                        state <= S_DATA;
                        dcnt  <= 2'd0;
                        accum <= 6'd0;
                        sof   <= 1'b1;    // signal start of frame to parser
                    end
                    // else: still eating 0x55 preamble dibits (rxd==01), stay
                end

                // ------------------------------------------------------------------
                // DATA: assemble 4 dibits into one byte, LSB first
                //       Byte layout: dibit0→b[1:0],  dibit1→b[3:2],
                //                    dibit2→b[5:4],  dibit3→b[7:6]
                // ------------------------------------------------------------------
                S_DATA: begin
                    if (!crs_dv && dcnt == 2'd0) begin
                        // CRS_DV fell at a byte boundary – clean end of frame
                        eof   <= 1'b1;
                        state <= S_IDLE;
                    end else begin
                        // Build byte
                        case (dcnt)
                            2'd0: accum[1:0] <= rxd;
                            2'd1: accum[3:2] <= rxd;
                            2'd2: accum[5:4] <= rxd;
                            2'd3: begin
                                byte_out <= {rxd, accum[5:0]};   // b[7:6]=rxd
                                vld      <= 1'b1;
                                // If CRS_DV deasserting on last byte boundary:
                                if (!crs_dv) begin
                                    eof   <= 1'b1;
                                    state <= S_IDLE;
                                end
                            end
                        endcase
                        dcnt <= dcnt + 1'b1;   // wraps 3→0 automatically
                    end
                end

            endcase
        end
    end

endmodule

`default_nettype wire
